// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Profile from "../Profile/Profile.bs.mjs";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

var menu = [
  "All",
  "About",
  "Projects",
  "Media"
];

var iconColor = "bg-clip-text text-transparent bg-gradient-to-r from-violet-400 to-blue-500";

function Header(props) {
  var handle = props.handle;
  var state = props.state;
  var colorMenu = function (menu, state) {
    var match = menu === state;
    if (match) {
      return "bg-white";
    } else {
      return "";
    }
  };
  return JsxRuntime.jsxs("header", {
              children: [
                JsxRuntime.jsx(Profile.Title.make, {
                      color: iconColor
                    }),
                JsxRuntime.jsx("div", {
                      children: Belt_Array.mapWithIndex(menu, (function (i, x) {
                              return JsxRuntime.jsx("div", {
                                          children: JsxRuntime.jsx("div", {
                                                children: x,
                                                className: ""
                                              }),
                                          className: "py-1 px-3 " + colorMenu(x, state) + " rounded-full cursor-pointer hover:text-gray-400 transition-colors duration-300",
                                          id: x,
                                          onClick: Curry.__1(handle)
                                        }, String(i));
                            })),
                      className: "flex p-2 gap-2 menu-item rounded-3xl"
                    }),
                JsxRuntime.jsx("a", {
                      children: JsxRuntime.jsx("p", {
                            children: "Contact"
                          }),
                      className: "cursor-pointer hover:underline",
                      href: "mailto:kemalsmy@gmail.com"
                    })
              ],
              className: "flex justify-between items-center"
            });
}

var make = Header;

export {
  menu ,
  iconColor ,
  make ,
}
/* Profile Not a pure module */
