// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as JsxRuntime from "react/jsx-runtime";

var description = "Curious data analyst venturing into the world of full-stack Software Engineering, fueled by a passion for data-driven innovation.";

function Bio(props) {
  var arrange = props.arrange;
  var toggle = props.toggle;
  var state = props.state;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("img", {
                              src: "logo.png"
                            }),
                        JsxRuntime.jsxs("button", {
                              children: [
                                JsxRuntime.jsx("img", {
                                      className: "rotate-90 hover:rotate-0 transition-all duration-100",
                                      height: "14",
                                      src: "sync.svg",
                                      width: "14"
                                    }),
                                JsxRuntime.jsx("p", {
                                      children: arrange === true ? "Random" : "Arrange",
                                      className: "hover:text-gray-400",
                                      onClick: (function (param) {
                                          Curry._1(toggle, (function (param) {
                                                  return arrange !== true;
                                                }));
                                        })
                                    })
                              ],
                              className: "border-2 hover:border-4 border-slate-200 rounded-xl flex justify-center items-center gap-2 py-1 px-3 transition-all duration-100"
                            })
                      ],
                      className: "flex justify-between items-start"
                    }),
                JsxRuntime.jsx("p", {
                      children: description
                    })
              ],
              className: "" + (
                state === "About" || state === "All" ? "" : "opacity-20"
              ) + " bg-white p-8 rounded-3xl space-y-4 col-span-2 hover:scale-105 transition-all duration-200 cursor-pointer"
            });
}

var make = Bio;

export {
  description ,
  make ,
}
/* react/jsx-runtime Not a pure module */
