// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Tech(props) {
  var state = props.state;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("img", {
                      src: "tech.svg"
                    }),
                JsxRuntime.jsxs("a", {
                      children: [
                        JsxRuntime.jsx("img", {
                              className: " ",
                              height: "20",
                              src: "arrow.svg",
                              width: "20"
                            }),
                        JsxRuntime.jsx("p", {
                              children: "Tech",
                              className: ""
                            })
                      ],
                      className: "absolute bottom-4 left-4 flex bg-white py-1 px-3 rounded-full hover:border-4 border-gray-200 gap-2 transition-all duration-100 ease-in-out",
                      href: "https://github.com/kemalmao19"
                    })
              ],
              className: "relative bg-pink-300 flex justify-center items-center w-full h-full " + (
                state === "About" || state === "All" ? "" : "opacity-20"
              ) + "\n        p-4\n          hover:scale-105 transition-all duration-200 cursor-pointer rounded-3xl"
            });
}

var make = Tech;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
