// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

var userName = "Kemalmao";

function Profile$Title(props) {
  return JsxRuntime.jsx("h1", {
              children: userName,
              className: "" + props.color + " font-logo text-3xl font-bold p-3"
            });
}

var Title = {
  make: Profile$Title
};

export {
  userName ,
  Title ,
}
/* react/jsx-runtime Not a pure module */
