// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Bio from "./List/About/Bio.bs.mjs";
import * as Blog from "./List/Media/Blog.bs.mjs";
import * as Tech from "./List/About/Tech.bs.mjs";
import * as React from "react";
import * as Github from "./List/Projects/Github.bs.mjs";
import * as Twitter from "./List/About/Twitter.bs.mjs";
import * as AdoptHunt from "./List/Projects/AdoptHunt.bs.mjs";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

function Cards(props) {
  var state = props.state;
  var match = React.useState(function () {
        return true;
      });
  var isArranged = match[0];
  var arrayData = [
    JsxRuntime.jsx(Bio.make, {
          state: state,
          toggle: match[1],
          arrange: isArranged,
          id: "About"
        }),
    JsxRuntime.jsx(Twitter.make, {
          state: state,
          id: "About"
        }),
    JsxRuntime.jsx(AdoptHunt.make, {
          state: state,
          id: "Projects"
        }),
    JsxRuntime.jsx(Github.make, {
          state: state,
          id: "Projects"
        }),
    JsxRuntime.jsx(Tech.make, {
          state: state,
          id: "About"
        }),
    JsxRuntime.jsx(Blog.make, {
          state: state,
          id: "Media"
        })
  ];
  var random = function (arrange, array) {
    if (arrange) {
      return Belt_Array.map(array, (function (item) {
                    return item;
                  }));
    } else {
      return Belt_Array.map(Belt_Array.shuffle(array), (function (item) {
                    return item;
                  }));
    }
  };
  return JsxRuntime.jsx("div", {
              children: random(isArranged, arrayData),
              className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 my-10 transition-transform duration-500 ease-in-out"
            });
}

var make = Cards;

export {
  make ,
}
/* Bio Not a pure module */
